### ISSUE TITLE
Prompt with color

### ISSUE THREAD

**Issue by lebojo** [MrLixam/minishell42#1]
Hello, you will have a problem with coloring prompt, because when using add_history() it will fckd up cause readling will count every color code as char and add it to length.

If you test 2 cmds, and then try to go to history WITH an actual prompt (someting in prompt) it will fckd up!

I was stuck on that problem for like 2 weeks, hope it'll help you <3

GLHF

**Comment by MrLixam** [comment]
hi, first of all, thanks for checking out that kind of thing :)
secondly, i'm not exactly getting what error you're refering to? just for context, the prompt here is the part that isn't saved in the history, readline makes it possible to add some

**Comment by MrLixam** [comment]
missclick, as I was writing, prompt is just used to add in front of the user added command line
could you show me how to reproduce the bug?

**Comment by lebojo** [comment]
For sure!

Looks my code:
<img width="293" alt="Capture d’écran 2023-10-17 à 09 02 58" src="https://github.com/MrLixam/minishell42/assets/48327357/17e7f379-3722-4f40-a58c-b9027add6bec">

It's my func for create the prompt:
<img width="555" alt="Capture d’écran 2023-10-17 à 09 03 25" src="https://github.com/MrLixam/minishell42/assets/48327357/caefbea9-669f-42f6-8589-feeb9cd2d3ad">

It's similar tou yours, cause of colors.

If you try to run your minishell, with the add_history, it will bug.

To reproduce:

- run minishell (with a history cmd)
- run 3 or +  differents cmd (like "ls", "env" or "ls -l")
- press up arrow key, then space, then up again

Then you will see the "bug"! 

Of course I consider that the minishell is working ahahah.

If you want to try, on my account I've almost finished my minishell, and you can clone it to see. I just put in comment de "create_prompt" function with color (and there is one without color under, which is the one I use)

Hope it helped!

**Comment by MrLixam** [comment]
can't seem to reproduce at home / don't see the bug if it is present, will try to reproduce once in campus, thanks for the insight, will keep informed once I manage, or not, to recreate the bug

**Comment by lebojo** [comment]
It’s a bug only on mac, I don’t know why, but on linux it seems to be ok…JordanLe 17 oct. 2023 à 09:47, Liam Vincent ***@***.***> a écrit :﻿
can't seem to reproduce at home / don't see the bug if it is present, will try to reproduce once in campus, thanks for the insight, will keep informed once I manage, or not, to recreate the bug

**Comment by MrLixam** [comment]
well, my campus runs only on linux, so should not be a problem, at least for now (ps: je viens de remarquer mais on est tout deux français il semblerait :p)
